name: ci
on:
  push:
    branches: [develop, main]
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: sbt/setup-sbt@v1
      - run: 'sbt "; +scalafmtCheckAll; scalafmtSbtCheck" "; scalafixEnable; scalafix --check; test:scalafix --check"'
  mimaReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{matrix.java}}
      - uses: sbt/setup-sbt@v1
      - run: 'sbt "++${{matrix.scala}} mimaReportBinaryIssues"'
    strategy:
      matrix:
        java:
          - "17"
          - "21"
        scala:
          - "2.12.21"
          - "2.13.18"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{matrix.java}}
      - uses: sbt/setup-sbt@v1
      - run: 'sbt "++${{matrix.scala}} test"'
    strategy:
      matrix:
        java:
          - "17"
          - "21"
        scala:
          - "2.12.21"
          - "2.13.18"
  testWithCoverageReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: sbt/setup-sbt@v1
      - run: sbt "++2.12.21" coverage clean test coverageReport
      - run: bash <(curl -s https://codecov.io/bash)
